export enum Status {
  EM_ABERTO = 'EM ABERTO',
  REJEITADO = 'REJEITADO',
  CANCELADO = 'CANCELADO',
  AGUARDANDO_PAGAMENTO = 'AGUARDANDO PAGAMENTO',
  RECOLHIDO = 'RECOLHIDO',
  PAGO = 'PAGO',
  FINALIZADO = 'FINALIZADO',
}
